# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AmicaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui,QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import QMovie
from PyQt5 import QtGui
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from PyQt5.QtCore import Qt, QTimer, QTime, QDate
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AMICA(object):
    def setupUi(self, AMICA):
        AMICA.setObjectName("AMICA")
        AMICA.resize(1410, 898)
        self.centralwidget = QtWidgets.QWidget(AMICA)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(4, 5, 1471, 941))
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap("D:/GUIMaterial/b3.jpg"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")

        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(130, 130, 1151, 431))
        self.bg_1.setStyleSheet("background-color: rgb(127, 3, 51);")
        self.bg_1.setText("")
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")

        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(140, 140, 1131, 411))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("D:/GUIMaterial/b2.gif"))
        self.Gif_1.setObjectName("Gif_1")

        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(120, 550, 401, 301))
        self.Gif_2.setStyleSheet("border-radius:none;")
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("D:/GUIMaterial/VoiceLogo.gif"))
        self.Gif_2.setObjectName("Gif_2")

        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(1040, 40, 221, 151))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("D:/GUIMaterial/b4.gif"))
        self.Gif_3.setObjectName("Gif_3")

        self.txt_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_time.setGeometry(QtCore.QRect(850, 680, 251, 41))
        self.txt_time.setStyleSheet("background-color:Transparent;\n"
"border-color: rgb(255, 5, 9);\n"
"border-radius:None;")
        self.txt_time.setObjectName("txt_time")
        self.txt_time_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_time_2.setGeometry(QtCore.QRect(1230, 830, 251, 41))
        self.txt_time_2.setStyleSheet("background-color:Transparent;\n"
"border-color: rgb(255, 5, 9);\n"
"border-radius:None;")
        self.txt_time_2.setObjectName("txt_time_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(1000, 310, 251, 71))
        self.bg_3.setStyleSheet("background-color: rgb(255, 10, 42);")
        self.bg_3.setText("")
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")

        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(1000, 400, 251, 71))
        self.bg_4.setStyleSheet("background-color: rgb(255, 10, 42);")
        self.bg_4.setText("")
        self.bg_4.setScaledContents(True)
        self.bg_4.setObjectName("bg_4")

        self.txt_Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_Time.setGeometry(QtCore.QRect(1010, 320, 231, 51))
        self.txt_Time.setStyleSheet("border-color: rgb(255, 109, 25);\n"
"background-color:Transparent;")
        self.txt_Time.setObjectName("txt_Time")
        self.txt_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_Date.setGeometry(QtCore.QRect(1010, 410, 231, 51))
        self.txt_Date.setStyleSheet("border-color: rgb(255, 109, 25);\n"
"background-color:Transparent;")
        self.txt_Date.setObjectName("txt_Date")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(830, 630, 451, 101))
        self.bg_2.setStyleSheet("background-color: rgb(127, 3, 51);")
        self.bg_2.setText("")
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 650, 411, 71))
        self.pushButton.setStyleSheet("font: 75 italic 24pt \"Palatino Linotype\";\n"
"border-color: rgb(35, 255, 49);\n"
"color:rgb(113, 11, 255);\n"
"border-radius:None;\n"
"background-color: Transparent;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(830, 750, 451, 101))
        self.bg_5.setStyleSheet("background-color: rgb(127, 3, 51);")
        self.bg_5.setText("")
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 770, 411, 71))
        self.pushButton_2.setStyleSheet("font: 75 italic 24pt \"Palatino Linotype\";\n"
"border-color: rgb(35, 255, 49);\n"
"color:rgb(113, 11, 255);\n"
"border-radius:None;\n"
"background-color: Transparent;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.Background.raise_()
        self.Gif_3.raise_()
        self.Gif_2.raise_()
        self.bg_1.raise_()
        self.Gif_1.raise_()
        self.txt_time.raise_()
        self.txt_time_2.raise_()
        self.bg_3.raise_()
        self.bg_4.raise_()
        self.txt_Time.raise_()
        self.txt_Date.raise_()
        self.bg_2.raise_()
        self.pushButton.raise_()
        self.bg_5.raise_()
        self.pushButton_2.raise_()
        AMICA.setCentralWidget(self.centralwidget)

        self.retranslateUi(AMICA)
        QtCore.QMetaObject.connectSlotsByName(AMICA)

    def retranslateUi(self, AMICA):
        _translate = QtCore.QCoreApplication.translate
        AMICA.setWindowTitle(_translate("AMICA", "MainWindow"))
        self.txt_time.setHtml(_translate("AMICA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.txt_time_2.setHtml(_translate("AMICA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("AMICA", "START"))
        self.pushButton_2.setText(_translate("AMICA", "QUIT"))




if __name__ == "__main__":
    import sys


    app = QtWidgets.QApplication(sys.argv)

    AMICA = QtWidgets.QMainWindow()
    ui = Ui_AMICA()
    ui.setupUi(AMICA)
    AMICA.show()
    sys.exit(app.exec_())
